### PR TITLE
Fix remove phrase incorrect behavior

### LINKED ISSUE #192: [Bug] Remove / Delete phrase incorrect behavior
Even though I don't have any phrase in the editor, once I click the "Remove" button, it'll still pop up a windows to ask "Do you want to delete this phrase?".

Maybe the button should be disabled if there is no phrase been selected.

### PR DESCRIPTION
**Pull request by hwhung0111**
Fixed #192 .
Checking the selection phrases instead of only checking if there is no phrase.
I squashed my commit, PR #200.

### CODE REVIEW

File: src/view/ChewingEditor.cpp [hunk 1]
```diff
@@ -193,6 +193,8 @@ void ChewingEditor::showAbout()
 
 void ChewingEditor::showDeleteConfirmWindow()
 {
+    if(!ui_.get()->userphraseView->selectionModel()->selectedIndexes().size()) return;
```
Comment (hwhung0111) [inline src/view/ChewingEditor.cpp]: How can I update the file in this PR?

Comment (Billy4195) [inline src/view/ChewingEditor.cpp]: you can use git commit --amend, then push on your branch

**Comment by david50407** [comment]
[Squash](https://git-scm.com/book/zh-tw/v1/Git-工具-重寫歷史) your commits first.

File: src/view/ChewingEditor.cpp (hunk 1 above)
Comment (hwhung0111) [inline src/view/ChewingEditor.cpp]: @Billy4195 Thank you.

**Comment by hwhung0111** [comment]
@david50407 I have squashed my commits.

**Comment by jserv** [comment]
Commit message "check the selection phares are bigger than one" is not valid English expression.

**Comment by jserv** [comment]
Don't mention `issue #192` in the subject of Git commit messages. Instead, do it within body.
