### PR TITLE
 Phrase can be preserved when the "add" step in "modify" is failed.

### LINKED ISSUE #75: Modify/Add phrase message and the modification failed phrase should not be removed.
When I modify a existing phrase, the message shows "Add new phrase successful" rather than "Modify a phrase successful" . 

I add a new phrase 耶(一ㄝ)
e

And then I modify it to 一ㄝˋ, but the message above shows "Add new phrase 耶(一ㄝˋ) successful" . 
r

I think it should be some modify message like "Modify phrase 耶(一ㄝ) to 耶(一ㄝˋ) successful" because I didn't add any new phrase into phrase list.

Besides, if Add failed, the message should be "Add new phrase 耶(一ㄝ) failed" while if Modification failed, the message should be "Modify phrase 耶(一ㄝ) to 耶(一ㄝˋ) failed" instead of "Remove 1 phrase successful", and the original phrase before modification should not be removed. (in this example , the phrase 耶(一ㄝ) should exists in list)

### PR DESCRIPTION
**Pull request by jeffreyhc**
This will close #75  #109 

When the "add" step is failed, the function will re-add the original phrase back.

This is my first pull request, wherever I can improve, please tell me.

### CODE REVIEW

**Comment by jserv** [comment]
Please improve your GIT commit messages.

**Comment by jserv** [comment]
The first line of GIT commit messages should be the summary of the change.
Reference: http://chris.beams.io/posts/git-commit/

**Comment by jeffreyhc** [comment]
Thanks for your advice and reference, but I have some problem of the commit log...
After I rewrite the commit log(use git rebase -i), I can't push new record to the master branch 
because of the diverged. Then I merge the record, and now the record becomes more
complicated.

**Comment by Chocobo1** [comment]
>I can't push new record to the master branch because of the diverged

use `git push -f`

>Maybe I can re-post a new PR to solve this situation?

Please no. And remove the `Merge branch ....` commit.

**Comment by jeffreyhc** [comment]
Sorry I don't know how to remove that commit,
should I rebase to the `fbe5896` then `git push -f` ?

Thanks for your advice.

**Comment by Chocobo1** [comment]
>Sorry I don't know how to remove that commit,

search for git remove commit. I'll let you learn on your own.

>should I rebase to the fbe5896 then git push -f ?

rebase should be revert.

File: src/view/UserphraseView.cpp [hunk 1]
```diff
@@ -75,6 +79,12 @@ void UserphraseView::addPhrase(int result)
     }
 
     emit model()->add(phrase, bopomofo);
+    
+    if (dialogType_ == DIALOG_MODIFY) {
+	if(model()->getAddResult() <= 0) {
```
Comment (Chocobo1) [inline src/view/UserphraseView.cpp]: indention and space between `if` & `(`

File: src/model/UserphraseModel.h [hunk 2]
```diff
@@ -45,6 +45,7 @@ class UserphraseModel final: public QAbstractListModel {
 
     const Userphrase *getUserphrase(const QModelIndex& idx);
 
+    int getAddResult(){return addResult;}
```
Comment (Chocobo1) [inline src/model/UserphraseModel.h]: `int getAddResult() const {...`: const and space.

File: src/view/UserphraseView.cpp [hunk 3]
```diff
@@ -75,6 +79,12 @@ void UserphraseView::addPhrase(int result)
...
+            emit model()->add(originalPhrase, originalBopomofo);
```
Comment (david50407) [inline src/view/UserphraseView.cpp]: will this get the original frequency to the re-added phrase?

File: src/view/UserphraseView.h [hunk 4]
```diff
@@ -64,4 +64,7 @@ public slots:
     UserphraseViewMenu *menu_;
 
     bool dialogType_;
+
+    std::shared_ptr<QString> originalPhrase;
```
Comment (Chocobo1) [inline src/view/UserphraseView.h]: why `std::shared_ptr<QString>`?
just `QString` is not enough?

File: src/model/UserphraseSortFilterProxyModel.h [hunk 5]
```diff
@@ -42,6 +42,7 @@ class UserphraseSortFilterProxyModel final : public QSortFilterProxyModel {
 
     const Userphrase *getUserphrase(const QModelIndex& idx);
 
+    int getAddResult();
```
Comment (Chocobo1) [inline src/model/UserphraseSortFilterProxyModel.h]: you forgot to initialize it...

File: src/model/UserphraseModel.h [hunk 6]
```diff
@@ -71,4 +72,5 @@ public slots:
 
     std::unique_ptr<ChewingContext, void (*)(ChewingContext*)> ctx_;
     UserphraseSet userphrase_;
+    int addResult;
```
Comment (Chocobo1) [inline src/model/UserphraseModel.h]: you forgot to initialize it...

File: src/view/UserphraseView.cpp (hunk 1 above)
Comment (Chocobo1) [inline src/view/UserphraseView.cpp]: `model()->sourceModel()->getAddResult()` and revert all changes in `UserphraseSortFilterProxyModel.*`

File: src/view/UserphraseView.h (hunk 4 above)
Comment (jeffreyhc) [inline src/view/UserphraseView.h]: No, because the interface in `UserphraseSortFilterProxyModel` 
need `std::shared_ptr<QString>`, and I think I should keep the consistency 
of the previous function call of model()->add()

File: src/view/UserphraseView.cpp (hunk 3 above)
Comment (jeffreyhc) [inline src/view/UserphraseView.cpp]: Do the "original frequency" means how ofter the user type them?
Well, I didn't consider it, where does the editor deal with it?
May be I can take it a look.

**Comment by jeffreyhc** [comment]
@Chocobo1 After I finish the edit, should I make a new commit or combine this to previous commit?

File: src/view/UserphraseView.h (hunk 4 above)
Comment (Chocobo1) [inline src/view/UserphraseView.h]: for now, it's ok to use `std::shared_ptr<QString>` :\

-

The reason of using `std::shared_ptr<QString>` in this case is flawed IMO:
`QString` already has the nature of ["implict sharing"](http://doc.qt.io/qt-5/implicit-sharing.html) which means it doesn't need `std::shared_ptr` to help maximize resource usage and minimize copying.
This should be refactored in another PR....

File: src/view/UserphraseView.cpp [hunk 7]
```diff
@@ -53,9 +54,12 @@ void UserphraseView::showModifyUserphraseDialog()
     dialogType_ = DIALOG_MODIFY;
 
     auto userphrase = model()->getUserphrase(selectionModel()->selectedIndexes().first());
-
     UserphraseDialog_->setText(userphrase->phrase_, userphrase->bopomofo_);
     UserphraseDialog_->setWindowTitle(tr("Modify phrase"));
+    
+    *originalPhrase = UserphraseDialog_->getPhrase();
```
Comment (Chocobo1) [inline src/view/UserphraseView.cpp]: `userphrase->phrase_`?

File: src/view/UserphraseView.cpp [hunk 8]
```diff
@@ -53,9 +54,12 @@ void UserphraseView::showModifyUserphraseDialog()
...
+    *originalBopomofo = UserphraseDialog_->getBopomofo();
```
Comment (Chocobo1) [inline src/view/UserphraseView.cpp]: `userphrase->bopomofo_`?

**Comment by Chocobo1** [comment]
>@Chocobo1 After I finish the edit, should I make a new commit or combine this to previous commit?

just amend it.

File: src/view/UserphraseView.cpp (hunk 8 above)
Comment (jeffreyhc) [inline src/view/UserphraseView.cpp]: Ok, I will use `userphrase->phrase_` and `userphrase->bopomofo_` to replace `UserphraseDialog_->getPhrase()`, `UserphraseDialog_->getBopomofo()` (I misthought before)

I have another question: should I replace the parameter of `UserphraseDialog_->setText(userphrase->phrase_, userphrase->bopomofo_)` to UserphraseDialog_->setText(*originalPhrase, *originalBopomofo)?

Comment (Chocobo1) [inline src/view/UserphraseView.cpp]: no need to change that

File: src/view/UserphraseView.cpp [hunk 9]
```diff
@@ -75,6 +79,12 @@ void UserphraseView::addPhrase(int result)
     }
 
     emit model()->add(phrase, bopomofo);
+    
+    if (dialogType_ == DIALOG_MODIFY) {
+	if (model()->sourceModel()->getAddResult() <= 0) {
```
Comment (jserv) [inline src/view/UserphraseView.cpp]: Use the consistent coding style.

Comment (jeffreyhc) [inline src/view/UserphraseView.cpp]: What do you mean "consistent coding style"?
Is there any thing can be referenced?

Comment (czchen) [inline src/view/UserphraseView.cpp]: I think you shall ensure the indent is the same. Since this project has `.editorconfig`, you can find a suitable plugin for your editor in <http://editorconfig.org/>.

Comment (jeffreyhc) [inline src/view/UserphraseView.cpp]: Thanks for your information, I will try this plugin and modify my code later!

**Comment by jserv** [comment]
@jeffreyhc : Can you rework the patch upon the review? Also, please read the article [How to Write a Git Commit Message](http://chris.beams.io/posts/git-commit/) carefully.

**Comment by jeffreyhc** [comment]
@jserv : sorry I don't fully understand. I have modified the code other developers advised before, and referenced that article to write commit message.
I think next I can study for the use frequency of userphrase in libchewing and try to integrate use frequency to the re-add userphrase mechanism.
But for this commit, I have no idea what I can do further.

**Comment by jserv** [comment]
@jeffreyhc : I could not find the revised patch [here](https://github.com/chewing/chewing-editor/pull/149/commits). Ensure the submission of your changes.

File: src/model/UserphraseSortFilterProxyModel.cpp [hunk 10]
```diff
@@ -53,3 +53,4 @@ const Userphrase *UserphraseSortFilterProxyModel::getUserphrase(const QModelInde
 {
     return sourceModel()->getUserphrase(mapToSource(idx));
 }
+
```
Comment (Chocobo1) [inline src/model/UserphraseSortFilterProxyModel.cpp]: revert this.

File: src/model/UserphraseSortFilterProxyModel.h [hunk 11]
```diff
@@ -41,7 +41,6 @@ class UserphraseSortFilterProxyModel final : public QSortFilterProxyModel {
     }
 
     const Userphrase *getUserphrase(const QModelIndex& idx);
-
```
Comment (Chocobo1) [inline src/model/UserphraseSortFilterProxyModel.h]: and this.

**Comment by jeffreyhc** [comment]
@Chocobo1 Hi, I've undone the style change. Does there anything I need to correct?

**Comment by jserv** [comment]
@jeffreyhc The statement, "Repair the mechanism of modify phrase in UserphraseView", is meaningless. You should summarize the changes and motivation in the first line of GIT commit messages.

**Comment by jeffreyhc** [comment]
@jserv How about "Fix the modify mechanism by re-adding deleted phrase"

**Comment by jserv** [comment]
I would write down as following:
```
Reclaim the phrase during "add" manipulation

Close #75
```

**Comment by jeffreyhc** [comment]
Shall I still keep the body of the commit message?
How about modify the message to:

Reclaim the phrase during "add" manipulation

Close #75

The phrase can be preserved when the "add" step in "modify" is failed.
After a new phrase is added, the selection of the original phrase in
chewing-editor seems to be reset, then the remove() in UserphaseView
will lost the remove target.
So I check the modified phrase add to the database successfully or not,
If the adding is fail, then re-add the original phrase.

See also: #109

**Comment by jserv** [comment]
@jeffreyhc : Of course, you need message body as well. I will merge your contribution after you push the revised commit.

By the way, check this: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by jserv** [comment]
@jeffreyhc : Separate subject from body with a blank line.
Reference: http://chris.beams.io/posts/git-commit/

**Comment by jeffreyhc** [comment]
@jserv So my commit message should only one blank line between subject and body? I thought the content of body can also be separated by blank line

File: src/view/UserphraseView.cpp [hunk 12]
```diff
@@ -17,7 +17,6 @@
  * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
  */
 
-#include "UserphraseModel.h"
```
Comment (jserv) [inline src/view/UserphraseView.cpp]: Why?

Comment (jeffreyhc) [inline src/view/UserphraseView.cpp]: I deleted it at first because I thought that code is mine(forgot to use git diff for check),
also, the code can execution well in spite of the deletion of the include.
And I think we don't need unnecessary include so I keep the deletion.

Or I shouldn't change the previous code when I cooperate with others in a project?

Comment (jserv) [inline src/view/UserphraseView.cpp]: Always concentrate on the functional and effective changes!

Comment (jeffreyhc) [inline src/view/UserphraseView.cpp]: OK, I see. And I've fixed it.

File: src/model/UserphraseModel.h (hunk 6 above)
Comment (jserv) [inline src/model/UserphraseModel.h]: no further rework?

Comment (jeffreyhc) [inline src/model/UserphraseModel.h]: @jserv What do you mean?

Comment (jserv) [inline src/model/UserphraseModel.h]: @jeffreyhc : You should reply to the code review from @Chocobo1 .

Comment (jeffreyhc) [inline src/model/UserphraseModel.h]: I initialize it in UserphraseModel.cpp:55,
or I should initialize the variable in header?

Comment (jserv) [inline src/model/UserphraseModel.h]: @jeffreyhc : You should convince @Chocobo1 with the deterministic explanation.

Comment (jeffreyhc) [inline src/model/UserphraseModel.h]: Sorry, it was my fault, I should reply the code review from @Chocobo1 after I modify my code.
I initialize the variable in the initialization list of UserphraseModel, because I want to keep the same coding style.

Comment (jeffreyhc) [inline src/model/UserphraseModel.h]: @Chocobo1 How do you think about my way to initialize the variable?

Comment (Chocobo1) [inline src/model/UserphraseModel.h]: >How do you think about my way to initialize the variable?

following the standard, it's ok.

I've notice another thing. `addResult` doesn't follow the coding style other private class member use: all lowercase and postfix a underscore.
This applies to other places, please check.

Comment (jeffreyhc) [inline src/model/UserphraseModel.h]: @Chocobo1 : I've fix it.

**Comment by jserv** [comment]
@jeffreyhc : Thanks for your contribution!
